openapi: 3.0.0
info:
  title: Lovelystay API doc
  version: 1.0.0
  description: "This the API documentation for Lovelystay server"
  contact:
    name: Tolu Ezekiel
    email: ezekiel2easy@gmail.com
    url: ''
  license:
    name: Proprietary - All rights reserved
  x-github: https://gitlab.com
  termsOfService: ''
servers:
  - description: Localhost
    url: 'http://localhost:3000/'
  - description: Staging
    url: ''
  - description: Production
    url: ''
components:
  schemas:
    Health:
      type: "object"
      properties:
        status:
          type: string
        error:
          type: string
